baseURL = 'https://blog.ture.dev/'
languageCode = 'en-US'
title = "Ture's Tech Blog"
theme = 'machine-mind'

[params]
    siteDescription = "Ture's personal blog"
    mastodonHost = "mastodon.social"

[markup]
  [markup.goldmark.parser]
    attribute = true
    wrapStandAloneImageWithinParagraph = false

  [markup.goldmark.renderHooks]
    [markup.goldmark.renderHooks.image]
      enableDefault = true