baseURL = 'https://blog.ture.dev/'
languageCode = 'en-US'
title = "Ture's Tech Blog"
theme = 'machine-mind'

[params]
    siteDescription = "Ture's personal blog"
    mastodonHost = "mastodon.social"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.parser.attribute]
      block = true
      title = true

  [markup.goldmark.renderHooks]
    [markup.goldmark.renderHooks.image]
      enableDefault = true